% MATLAB Editor Run Commands
% @version 4
% It is recommended that you do not edit this file directly, but use the
% Run button. Changes made to comments that exist outside of a
% configuration will not be saved.

%% @name test_network
%  @associatedFile /MATLAB Drive/test_network.m
%  @mostRecentlyActioned true
%  @uniqueId 77025651

test_network

